### PR TITLE
GPS Navigation

### PR DESCRIPTION
**Pull request by haashimrehan**

### CODE REVIEW

**Comment by haashimrehan** [comment]
GPS tested on Jetson TX2

**Comment by haashimrehan** [comment]
GPS requires this [udev rule](https://github.com/MacRover/Rover/issues/35#issuecomment-1546782959) to work

**Comment by haashimrehan** [comment]
D435 and T265 Realsense Cameras require [this process](https://github.com/MacRover/Rover/issues/33#issuecomment-1546746544) to work

**Comment by haashimrehan** [comment]
due to the realsense process we'll also need to run the following command on the TX2 to get it to `catkin_make` without errors:

`touch $HOME/Rover/ROS_WS/simulation/CATKIN_IGNORE`

since `CATKIN_IGNORE` is already the `.gitignore`, this doesn't affect simulation development

**Comment by emcauliffe** [comment]
follow ups:

- [ ] set imu default to false

**Pull request merged**
